fix

diff --git a/.github/workflows/distribute.yaml b/.github/workflows/distribute.yaml
--- a/.github/workflows/distribute.yaml
+++ b/.github/workflows/distribute.yaml
@@ -41,18 +41,18 @@ jobs:
         id: check_repo
         run: |
           REPO_NAME="${{matrix.module}}"
-          RESPONSE=$(gh repo view Apollo-XIV/$REPO_NAME --json name --jq .name 2>/dev/null || echo "not found")
+          RESPONSE=$(gh repo view Apollo-XIV/$REPO_NAME --json name --jq .name || echo "not found")
           echo "Repository status: $RESPONSE"
           if [ "$RESPONSE" = "not found" ]; then
-            echo "::set-output name=repo_exists::false"
+            echo "repo_exists=false" >> $GITHUB_ENV
           else
-            echo "::set-output name=repo_exists::true"
+            echo "repo_exists=true" >> $GITHUB_ENV
           fi
 
       - name: Create repository if it does not exist
-        if: steps.check_repo.outputs.repo_exists == 'false'
+        if: env.repo_exists == 'false'
         run: |
-          gh repo create Apollo-XIV/${{matrix.module}} --public --confirm
+          gh repo create Apollo-XIV/${{matrix.module}} --public
         env:
           GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
 
